name: inkino
description: A new Flutter application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  xml: ^6.3.0
  flutter_redux: ^0.10.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  flutter_lints: ^5.0.0
  # image_test_utils: ^1.0.0 # still outdated, consider replacing if needed

flutter:
  uses-material-design: true

  assets:
    - assets/images/1x1_transparent.png
    - assets/images/powered_by_tmdb.png
    - assets/images/background_image.jpg
    - assets/images/logo.png