name: core
description: Common shared code for inKino mobile and web.
version: 0.0.1
#homepage: https://www.example.com
#author: ironman <email@example.com>

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  redux: ^5.0.0
  intl: ^0.19.0
  xml: ^6.3.0
  http: ^1.4.0
  reselect: ^0.5.0
  # key_value_store: ^1.0.0
  kt_dart: ^1.1.0
  shared_preferences: ^2.5.3

dev_dependencies:
  test: ^1.26.2
  mockito: ^5.4.5
  intl_translation: 0.20.1
